#cloud-config

coreos:
  etcd2:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new?size=3
    # specify the initial size of your cluster with ?size=X
    discovery: https://discovery.etcd.io/a8c36a5e968b606ffa1510165c2cbe21
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$private_ipv4:2379,http://$private_ipv4:4001
    initial-advertise-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://$private_ipv4:7001
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
users:
  - name: core
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDT2eU3Lyn81AIK3x8psCcyxmWXDF4IYsmaOt7uk1lsX+Z6dC5SJtNEAmx1U4jtq3aM+Sa3FBJq0/1sBIy462Dd74H4YRT3sM0+gJxMSG242FQ4x1fGmeBclOAqdcG1SOBCgLI0jxOMuRp8/7Eo9r0T746PktzljrV9IWeTCVD3ZpNeIOCn/iRxb4Tt91V9F6p+OXYoFoO4RWlpwms59WrPtSoCBl21jwH6/aGKUm+Q4BIK571Av1ii+puGS/vGrf8IHglYrohOO+RMTC4BfCvrZowI1J5OPgggs+Pf2wyDHpru2srdCbhG7Io5LIcimdMplUqRrKdbtD/nsqrBM4s9 gardnert@debian
    groups:
      - sudo
      - docker
